window.esdocSearchIndex = [
  [
    "cod-example/src/app/helpers/fetch.js~fetchresponse",
    "class/src/app/helpers/fetch.js~FetchResponse.html",
    "<span>FetchResponse</span> <span class=\"search-result-import-path\">cod-example/src/app/helpers/fetch.js</span>",
    "class"
  ],
  [
    "cod-example/src/app/helpers/jsonview.js~jsonview",
    "class/src/app/helpers/jsonview.js~JsonView.html",
    "<span>JsonView</span> <span class=\"search-result-import-path\">cod-example/src/app/helpers/jsonview.js</span>",
    "class"
  ],
  [
    "cod-example/src/app/main/index.js~main",
    "class/src/app/main/index.js~Main.html",
    "<span>Main</span> <span class=\"search-result-import-path\">cod-example/src/app/main/index.js</span>",
    "class"
  ],
  [
    "cod-example/src/app/main/controller.js~maincontroller",
    "class/src/app/main/controller.js~MainController.html",
    "<span>MainController</span> <span class=\"search-result-import-path\">cod-example/src/app/main/controller.js</span>",
    "class"
  ],
  [
    "cod-example/src/app/main/view-d3.js~maind3view",
    "class/src/app/main/view-d3.js~MainD3View.html",
    "<span>MainD3View</span> <span class=\"search-result-import-path\">cod-example/src/app/main/view-d3.js</span>",
    "class"
  ],
  [
    "cod-example/src/app/main/store.js~mainstore",
    "class/src/app/main/store.js~MainStore.html",
    "<span>MainStore</span> <span class=\"search-result-import-path\">cod-example/src/app/main/store.js</span>",
    "class"
  ],
  [
    "cod-example/src/app/main/view-json.js~mainview",
    "class/src/app/main/view-json.js~MainView.html",
    "<span>MainView</span> <span class=\"search-result-import-path\">cod-example/src/app/main/view-json.js</span>",
    "class"
  ],
  [
    "cod-example/src/app/main/viewmodel.js~mainviewmodel",
    "class/src/app/main/viewmodel.js~MainViewModel.html",
    "<span>MainViewModel</span> <span class=\"search-result-import-path\">cod-example/src/app/main/viewmodel.js</span>",
    "class"
  ],
  [
    "cod-example/src/app/helpers/noopview.js~noopview",
    "class/src/app/helpers/noopview.js~NoopView.html",
    "<span>NoopView</span> <span class=\"search-result-import-path\">cod-example/src/app/helpers/noopview.js</span>",
    "class"
  ],
  [
    "cod-example/src/app/helpers/observer.js~observer",
    "class/src/app/helpers/observer.js~Observer.html",
    "<span>Observer</span> <span class=\"search-result-import-path\">cod-example/src/app/helpers/observer.js</span>",
    "class"
  ],
  [
    "cod-example/src/app/helpers/simplepromise.js~simplepromise",
    "class/src/app/helpers/simplepromise.js~SimplePromise.html",
    "<span>SimplePromise</span> <span class=\"search-result-import-path\">cod-example/src/app/helpers/simplepromise.js</span>",
    "class"
  ],
  [
    "cod-example/src/app/helpers/fetch.js~fetch",
    "function/index.html#static-function-fetch",
    "<span>fetch</span> <span class=\"search-result-import-path\">cod-example/src/app/helpers/fetch.js</span>",
    "function"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~arraybuffer",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~ArrayBuffer",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~boolean",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Boolean",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~dataview",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~DataView",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~date",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Date",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~error",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Error",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~evalerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~EvalError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~float32array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Float32Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~float64array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Float64Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~function",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Function",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~generator",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Generator",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~generatorfunction",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~GeneratorFunction",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~infinity",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Infinity",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~int16array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Int16Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~int32array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Int32Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~int8array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Int8Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~internalerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~InternalError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~json",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~JSON",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~map",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Map",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~nan",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~NaN",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~number",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Number",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~object",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Object",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~promise",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Promise",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~proxy",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Proxy",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~rangeerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~RangeError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~referenceerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~ReferenceError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~reflect",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Reflect",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~regexp",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~RegExp",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~set",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Set",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~string",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~String",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~symbol",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Symbol",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~syntaxerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~SyntaxError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~typeerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~TypeError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~urierror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~URIError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint16array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Uint16Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint32array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Uint32Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint8array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Uint8Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint8clampedarray",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Uint8ClampedArray",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~weakmap",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~WeakMap",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~weakset",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~WeakSet",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~boolean",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~boolean",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~function",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~function",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~null",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~null",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~number",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~number",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~object",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~object",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~string",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~string",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~undefined",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~undefined",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~canvasrenderingcontext2d",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~CanvasRenderingContext2D",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~documentfragment",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~DocumentFragment",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~element",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~Element",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~event",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~Event",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~node",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~Node",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~nodelist",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~NodeList",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~xmlhttprequest",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~XMLHttpRequest",
    "external"
  ],
  [
    "src/app.js",
    "file/src/app.js.html",
    "src/app.js",
    "file"
  ],
  [
    "src/app/helpers/fetch.js",
    "file/src/app/helpers/fetch.js.html",
    "src/app/helpers/fetch.js",
    "file"
  ],
  [
    "src/app/helpers/fetch.js~fetchresponse#constructor",
    "class/src/app/helpers/fetch.js~FetchResponse.html#instance-constructor-constructor",
    "src/app/helpers/fetch.js~FetchResponse#constructor",
    "method"
  ],
  [
    "src/app/helpers/fetch.js~fetchresponse#data",
    "class/src/app/helpers/fetch.js~FetchResponse.html#instance-member-data",
    "src/app/helpers/fetch.js~FetchResponse#data",
    "member"
  ],
  [
    "src/app/helpers/fetch.js~fetchresponse#error",
    "class/src/app/helpers/fetch.js~FetchResponse.html#instance-member-error",
    "src/app/helpers/fetch.js~FetchResponse#error",
    "member"
  ],
  [
    "src/app/helpers/fetch.js~fetchresponse#status",
    "class/src/app/helpers/fetch.js~FetchResponse.html#instance-member-status",
    "src/app/helpers/fetch.js~FetchResponse#status",
    "member"
  ],
  [
    "src/app/helpers/jsonview.js",
    "file/src/app/helpers/jsonview.js.html",
    "src/app/helpers/jsonview.js",
    "file"
  ],
  [
    "src/app/helpers/jsonview.js~jsonview#init",
    "class/src/app/helpers/jsonview.js~JsonView.html#instance-method-init",
    "src/app/helpers/jsonview.js~JsonView#init",
    "method"
  ],
  [
    "src/app/helpers/jsonview.js~jsonview#onupdate",
    "class/src/app/helpers/jsonview.js~JsonView.html#instance-method-onUpdate",
    "src/app/helpers/jsonview.js~JsonView#onUpdate",
    "method"
  ],
  [
    "src/app/helpers/jsonview.js~jsonview#viewname",
    "class/src/app/helpers/jsonview.js~JsonView.html#instance-member-viewName",
    "src/app/helpers/jsonview.js~JsonView#viewName",
    "member"
  ],
  [
    "src/app/helpers/noopview.js",
    "file/src/app/helpers/noopview.js.html",
    "src/app/helpers/noopview.js",
    "file"
  ],
  [
    "src/app/helpers/noopview.js~noopview#init",
    "class/src/app/helpers/noopview.js~NoopView.html#instance-method-init",
    "src/app/helpers/noopview.js~NoopView#init",
    "method"
  ],
  [
    "src/app/helpers/noopview.js~noopview#onupdate",
    "class/src/app/helpers/noopview.js~NoopView.html#instance-method-onUpdate",
    "src/app/helpers/noopview.js~NoopView#onUpdate",
    "method"
  ],
  [
    "src/app/helpers/observer.js",
    "file/src/app/helpers/observer.js.html",
    "src/app/helpers/observer.js",
    "file"
  ],
  [
    "src/app/helpers/observer.js~observer#constructor",
    "class/src/app/helpers/observer.js~Observer.html#instance-constructor-constructor",
    "src/app/helpers/observer.js~Observer#constructor",
    "method"
  ],
  [
    "src/app/helpers/observer.js~observer#fire",
    "class/src/app/helpers/observer.js~Observer.html#instance-method-fire",
    "src/app/helpers/observer.js~Observer#fire",
    "method"
  ],
  [
    "src/app/helpers/observer.js~observer#subscribe",
    "class/src/app/helpers/observer.js~Observer.html#instance-method-subscribe",
    "src/app/helpers/observer.js~Observer#subscribe",
    "method"
  ],
  [
    "src/app/helpers/observer.js~observer#unsubscribe",
    "class/src/app/helpers/observer.js~Observer.html#instance-method-unsubscribe",
    "src/app/helpers/observer.js~Observer#unsubscribe",
    "method"
  ],
  [
    "src/app/helpers/simplepromise.js",
    "file/src/app/helpers/simplepromise.js.html",
    "src/app/helpers/simplepromise.js",
    "file"
  ],
  [
    "src/app/helpers/simplepromise.js~simplepromise#constructor",
    "class/src/app/helpers/simplepromise.js~SimplePromise.html#instance-constructor-constructor",
    "src/app/helpers/simplepromise.js~SimplePromise#constructor",
    "method"
  ],
  [
    "src/app/helpers/simplepromise.js~simplepromise#data",
    "class/src/app/helpers/simplepromise.js~SimplePromise.html#instance-member-data",
    "src/app/helpers/simplepromise.js~SimplePromise#data",
    "member"
  ],
  [
    "src/app/helpers/simplepromise.js~simplepromise#fail",
    "class/src/app/helpers/simplepromise.js~SimplePromise.html#instance-method-fail",
    "src/app/helpers/simplepromise.js~SimplePromise#fail",
    "method"
  ],
  [
    "src/app/helpers/simplepromise.js~simplepromise#isresolved",
    "class/src/app/helpers/simplepromise.js~SimplePromise.html#instance-member-isResolved",
    "src/app/helpers/simplepromise.js~SimplePromise#isResolved",
    "member"
  ],
  [
    "src/app/helpers/simplepromise.js~simplepromise#processcallbacks",
    "class/src/app/helpers/simplepromise.js~SimplePromise.html#instance-method-processCallbacks",
    "src/app/helpers/simplepromise.js~SimplePromise#processCallbacks",
    "method"
  ],
  [
    "src/app/helpers/simplepromise.js~simplepromise#reject",
    "class/src/app/helpers/simplepromise.js~SimplePromise.html#instance-method-reject",
    "src/app/helpers/simplepromise.js~SimplePromise#reject",
    "method"
  ],
  [
    "src/app/helpers/simplepromise.js~simplepromise#rejectcallbacks",
    "class/src/app/helpers/simplepromise.js~SimplePromise.html#instance-member-rejectCallbacks",
    "src/app/helpers/simplepromise.js~SimplePromise#rejectCallbacks",
    "member"
  ],
  [
    "src/app/helpers/simplepromise.js~simplepromise#resolve",
    "class/src/app/helpers/simplepromise.js~SimplePromise.html#instance-method-resolve",
    "src/app/helpers/simplepromise.js~SimplePromise#resolve",
    "method"
  ],
  [
    "src/app/helpers/simplepromise.js~simplepromise#successcallbacks",
    "class/src/app/helpers/simplepromise.js~SimplePromise.html#instance-member-successCallbacks",
    "src/app/helpers/simplepromise.js~SimplePromise#successCallbacks",
    "member"
  ],
  [
    "src/app/helpers/simplepromise.js~simplepromise#then",
    "class/src/app/helpers/simplepromise.js~SimplePromise.html#instance-method-then",
    "src/app/helpers/simplepromise.js~SimplePromise#then",
    "method"
  ],
  [
    "src/app/main/controller.js",
    "file/src/app/main/controller.js.html",
    "src/app/main/controller.js",
    "file"
  ],
  [
    "src/app/main/controller.js~maincontroller#init",
    "class/src/app/main/controller.js~MainController.html#instance-method-init",
    "src/app/main/controller.js~MainController#init",
    "method"
  ],
  [
    "src/app/main/controller.js~maincontroller#onfirstload",
    "class/src/app/main/controller.js~MainController.html#instance-method-onFirstLoad",
    "src/app/main/controller.js~MainController#onFirstLoad",
    "method"
  ],
  [
    "src/app/main/controller.js~maincontroller#onitemclick",
    "class/src/app/main/controller.js~MainController.html#instance-method-onItemClick",
    "src/app/main/controller.js~MainController#onItemClick",
    "method"
  ],
  [
    "src/app/main/index.js",
    "file/src/app/main/index.js.html",
    "src/app/main/index.js",
    "file"
  ],
  [
    "src/app/main/index.js~main#controller",
    "class/src/app/main/index.js~Main.html#instance-member-controller",
    "src/app/main/index.js~Main#controller",
    "member"
  ],
  [
    "src/app/main/index.js~main#init",
    "class/src/app/main/index.js~Main.html#instance-method-init",
    "src/app/main/index.js~Main#init",
    "method"
  ],
  [
    "src/app/main/index.js~main#store",
    "class/src/app/main/index.js~Main.html#instance-member-store",
    "src/app/main/index.js~Main#store",
    "member"
  ],
  [
    "src/app/main/index.js~main#view",
    "class/src/app/main/index.js~Main.html#instance-member-view",
    "src/app/main/index.js~Main#view",
    "member"
  ],
  [
    "src/app/main/index.js~main#viewmodel",
    "class/src/app/main/index.js~Main.html#instance-member-viewmodel",
    "src/app/main/index.js~Main#viewmodel",
    "member"
  ],
  [
    "src/app/main/store.js",
    "file/src/app/main/store.js.html",
    "src/app/main/store.js",
    "file"
  ],
  [
    "src/app/main/store.js~mainstore#init",
    "class/src/app/main/store.js~MainStore.html#instance-method-init",
    "src/app/main/store.js~MainStore#init",
    "method"
  ],
  [
    "src/app/main/store.js~mainstore#onupdate",
    "class/src/app/main/store.js~MainStore.html#instance-method-onUpdate",
    "src/app/main/store.js~MainStore#onUpdate",
    "method"
  ],
  [
    "src/app/main/view-d3.js",
    "file/src/app/main/view-d3.js.html",
    "src/app/main/view-d3.js",
    "file"
  ],
  [
    "src/app/main/view-d3.js~maind3view#init",
    "class/src/app/main/view-d3.js~MainD3View.html#instance-method-init",
    "src/app/main/view-d3.js~MainD3View#init",
    "method"
  ],
  [
    "src/app/main/view-d3.js~maind3view#onitemclick",
    "class/src/app/main/view-d3.js~MainD3View.html#instance-method-onItemClick",
    "src/app/main/view-d3.js~MainD3View#onItemClick",
    "method"
  ],
  [
    "src/app/main/view-d3.js~maind3view#onupdate",
    "class/src/app/main/view-d3.js~MainD3View.html#instance-method-onUpdate",
    "src/app/main/view-d3.js~MainD3View#onUpdate",
    "method"
  ],
  [
    "src/app/main/view-d3.js~maind3view#stage",
    "class/src/app/main/view-d3.js~MainD3View.html#instance-member-stage",
    "src/app/main/view-d3.js~MainD3View#stage",
    "member"
  ],
  [
    "src/app/main/view-json.js",
    "file/src/app/main/view-json.js.html",
    "src/app/main/view-json.js",
    "file"
  ],
  [
    "src/app/main/view-json.js~mainview#init",
    "class/src/app/main/view-json.js~MainView.html#instance-method-init",
    "src/app/main/view-json.js~MainView#init",
    "method"
  ],
  [
    "src/app/main/view-json.js~mainview#viewname",
    "class/src/app/main/view-json.js~MainView.html#instance-member-viewName",
    "src/app/main/view-json.js~MainView#viewName",
    "member"
  ],
  [
    "src/app/main/viewmodel.js",
    "file/src/app/main/viewmodel.js.html",
    "src/app/main/viewmodel.js",
    "file"
  ],
  [
    "src/app/main/viewmodel.js~mainviewmodel#data",
    "class/src/app/main/viewmodel.js~MainViewModel.html#instance-member-data",
    "src/app/main/viewmodel.js~MainViewModel#data",
    "member"
  ],
  [
    "src/app/main/viewmodel.js~mainviewmodel#init",
    "class/src/app/main/viewmodel.js~MainViewModel.html#instance-method-init",
    "src/app/main/viewmodel.js~MainViewModel#init",
    "method"
  ],
  [
    "src/app/main/viewmodel.js~mainviewmodel#onitemselected",
    "class/src/app/main/viewmodel.js~MainViewModel.html#instance-method-onItemSelected",
    "src/app/main/viewmodel.js~MainViewModel#onItemSelected",
    "method"
  ],
  [
    "src/app/main/viewmodel.js~mainviewmodel#onupdate",
    "class/src/app/main/viewmodel.js~MainViewModel.html#instance-method-onUpdate",
    "src/app/main/viewmodel.js~MainViewModel#onUpdate",
    "method"
  ],
  [
    "src/app/main/viewmodel.js~mainviewmodel#selecteditemid",
    "class/src/app/main/viewmodel.js~MainViewModel.html#instance-member-selectedItemId",
    "src/app/main/viewmodel.js~MainViewModel#selectedItemId",
    "member"
  ],
  [
    "src/bundle.js",
    "file/src/bundle.js.html",
    "src/bundle.js",
    "file"
  ],
  [
    "src/config.js",
    "file/src/config.js.html",
    "src/config.js",
    "file"
  ],
  [
    "src/locale.js",
    "file/src/locale.js.html",
    "src/locale.js",
    "file"
  ]
]